#pragma once

#include <SFML/Network.hpp>

enum class InternalPacketType : sf::Uint8
{
    None,
    INTERNAL_CONNECT_REQUEST,
    INTERNAL_CONNECT_ACCEPT,
    INTERNAL_DISCONNECT,
    INTERNAL_HEARTBEAT,
    INTERNAL_AR,
    INTERNAL_SESSION_JOIN_REQUEST,
    INTERNAL_SESSION_JOIN_ACCEPT,
    INTERNAL_SESSION_ON_JOIN,
    INTERNAL_SESSION_ON_LEAVE,
    USER_PACKET
};
